apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u6yrkk2ui-nodejs 
  janus-idp.io/tekton: u6yrkk2ui-nodejs
  backstage.io/kubernetes-id: u6yrkk2ui-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u6yrkk2ui-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml